name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write  # Ensure this is set if issues need to be created
      pull-requests: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "https://www.shecodes.io/"
          fail_action: true  # Ensure the action fails if issues are found
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}

