name: SonarQube CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Output Run ID
        run: echo ${{ github.run_id }}

      - name: Build SonarQube image
        run: |
          # docker build -t crswsmkpdevsan1.azurecr.io/sonarqube-custom:${{ github.run_id }} 
          docker images
